### ISSUE TITLE
unable to run it as a package

### ISSUE THREAD

**Issue by prakharchoudhary** [prakharchoudhary/UdacityMate#1]
when trying to run the package as:
`python3 udacitymate` terminal gives `no module named __main__` error.

**Comment by ankitjain28may** [comment]
Because your udacitymate.py is in another folder name udacitymate so you either need to call it inside the folder or you need to put this file outside the folder.

**Comment by prakharchoudhary** [comment]
or I can simply make a new file `__main__.py` which initializes the main function. This I don't have to run the script with a .py extension but only the folder name.
